package net.zephyr.fnafur.init.item_init;

import net.zephyr.fnafur.FnafUniverseRebuilt;
import net.zephyr.fnafur.client.gui.screens.creative_menu.ItemCategoriesManager;
import net.zephyr.fnafur.client.gui.screens.creative_menu.ItemCategory;
import net.zephyr.fnafur.init.block_init.BlockInit;

public class ItemCategoriesInit {

    public static final ItemCategory TILES = ItemCategory.create(ItemCategory.builder()
            .setID("tiles")
            .addItems(
                    ItemCategory.Entry.create(BlockInit.BLACK_WHITE_TILES,
                            BlockInit.BLACK_WHITE_TILES,
                            BlockInit.RED_BLUE_TILES,
                            BlockInit.RED_BLACK_TILES,
                            BlockInit.BLACK_BLUE_TILES,
                            BlockInit.DARK_BLUE_TILES,
                            BlockInit.BLACK_TILES,
                            BlockInit.RED_TILES,
                            BlockInit.WHITE_TILES,
                            BlockInit.GROUT_TILE,
                            BlockInit.DARK_GROUT_TILES
                    ),
                    ItemCategory.Entry.create(BlockInit.BLACK_TILE,
                            BlockInit.BLACK_TILE,
                            BlockInit.WHITE_TILE,
                            BlockInit.BLACK_CORNER_BROWN_TILE,
                            BlockInit.BLACK_GREEN_DIAGONAL_TILE,
                            BlockInit.CONCRETE_FLOOR_TILE
                    ),
                    ItemCategory.Entry.create(BlockInit.BLACK_WHITE_16_TILES,
                            BlockInit.BLACK_WHITE_16_TILES,
                            BlockInit.BLACK_WHITE_16_TILES_TRIM,
                            BlockInit.BLACK_BLUE_WALL_TILES,
                            BlockInit.BLACK_BLUE_WALL_TILES_TOP,
                            BlockInit.BLACK_RED_WALL_TILES,
                            BlockInit.BLACK_RED_WALL_TILES_TOP
                    ),
                    ItemCategory.Entry.create(BlockInit.TAN_16_CLEAN_TILES,
                            BlockInit.TAN_16_CLEAN_TILES,
                            BlockInit.TAN_16_SPACED_TILES,
                            BlockInit.TAN_RAINBOW_16_TILES,
                            BlockInit.TAN_16_TILES,
                            BlockInit.BLUE_TILES,
                            BlockInit.GREEN_TILES_BLACK_LINING,
                            BlockInit.EXTRUDED_BLACK_TILES,
                            BlockInit.KITCHEN_FLOOR
                    ),
                    ItemCategory.Entry.create(BlockInit.BRIGHT_YELLOW_TILES,
                            BlockInit.BRIGHT_PURPLE_TILES,
                            BlockInit.BRIGHT_NAVY_BLUE_TILES,
                            BlockInit.BRIGHT_BLUE_TILES,
                            BlockInit.BRIGHT_GREEN_TILES,
                            BlockInit.OFF_WHITE_TILES,
                            BlockInit.BRIGHT_YELLOW_TILES,
                            BlockInit.BRIGHT_WHITE_TILES,
                            BlockInit.BRIGHT_PINK_TILES,
                            BlockInit.BRIGHT_MAGENTA_TILES,
                            BlockInit.BRIGHT_ORANGE_TILES,
                            BlockInit.BRIGHT_BROWN_TILES,
                            BlockInit.WHITE_16_CLEAN_TILES,
                            BlockInit.WHITE_16_TILES
                    ),
                    ItemCategory.Entry.create(BlockInit.SMALL_BLACK_TILES,
                            BlockInit.SMALL_BLACK_TILES,
                            BlockInit.SMALL_BLACK_RED_TILES,
                            BlockInit.SMALL_BLUE_BLACK_TILES,
                            BlockInit.SMALL_BLUE_RED_TILES,
                            BlockInit.SMALL_CYAN_BLACK_TILES,
                            BlockInit.SMALL_DARK_BLUE_TILES,
                            BlockInit.SMALL_BIEGE_TILES,
                            BlockInit.POOL_FLOOR_SMALL_TILES,
                            BlockInit.BLUE_SMALL_TILES,
                            BlockInit.TURQUOISE_SMALL_TILES,
                            BlockInit.PURPLE_SMALL_TILES,
                            BlockInit.DARK_TAN_BRICKS,
                            BlockInit.SMALL_STONE_TILES
                    ),
                    ItemCategory.Entry.create(BlockInit.CEILING_TILES,
                            BlockInit.CEILING_TILES,
                            BlockInit.CEILING_TILES_STAINED,
                            BlockInit.BLACK_CEILING_TILE,
                            BlockInit.WHITE_CEILING_TILES,
                            BlockInit.CEILING_TILE_LIGHT
                    ),
                    ItemCategory.Entry.create(BlockInit.MOSAIC_BRICKS,
                            BlockInit.MOSAIC_BRICKS
                    )
            )
            .build()
    );

    public static final ItemCategory BRICKS = ItemCategory.create(ItemCategory.builder()
            .setID("bricks")
            .addItems(
                    ItemCategory.Entry.create(BlockInit.RED_BRICK_WALL_SMALL,
                            BlockInit.RED_BRICK_WALL_SMALL,
                            BlockInit.BRICK_WALL,
                            BlockInit.DIRTY_BRICKS,
                            BlockInit.SMALL_GRAY_BRICKS,
                            BlockInit.SMALL_LIGHT_GRAY_BRICKS,
                            BlockInit.METAL_PLATES,
                            BlockInit.ROUGH_METAL_PLATES
                    ),
                    ItemCategory.Entry.create(BlockInit.BRICK_WALL_DARKER,
                            BlockInit.BRICK_WALL_DARKER
                    ),
                    ItemCategory.Entry.create(BlockInit.TAN_THIN_BRICKS,
                            BlockInit.TAN_THIN_BRICKS,
                            BlockInit.VARIED_TAN_THIN_BRICKS,
                            BlockInit.BROWN_THIN_BRICKS,
                            BlockInit.RED_THIN_BRICKS,
                            BlockInit.ORANGE_THIN_BRICKS,
                            BlockInit.YELLOW_THIN_BRICKS,
                            BlockInit.GREEN_THIN_BRICKS,
                            BlockInit.CYAN_THIN_BRICKS,
                            BlockInit.PURPLE_THIN_BRICKS,
                            BlockInit.MAGENTA_THIN_BRICKS,
                            BlockInit.PINK_THIN_BRICKS,
                            BlockInit.GRAY_THIN_BRICKS,
                            BlockInit.WHITE_THIN_BRICKS
                    ),
                    ItemCategory.Entry.create(BlockInit.RED_BRICK_WALL_MIXED,
                            BlockInit.RED_BRICK_WALL_MIXED,
                            BlockInit.GRAY_BRICKS_WHITE_CEMENT,
                            BlockInit.TEAL_BRICKS,
                            BlockInit.RED_BRICKS_BLACK_GROUT,
                            BlockInit.BLUE_GRAY_BRICKS,
                            BlockInit.GREEN_BRICKS,
                            BlockInit.BLACK_BRICKS
                    ),
                    ItemCategory.Entry.create(BlockInit.BLUE_BRICKS,
                            BlockInit.BLUE_BRICKS
                    ),
                    ItemCategory.Entry.create(BlockInit.BRIGHT_BLUE_BRICKS,
                            BlockInit.BRIGHT_BLUE_BRICKS,
                            BlockInit.BRIGHT_NAVY_BLUE_BRICKS,
                            BlockInit.BRIGHT_GREEN_BRICKS,
                            BlockInit.BRIGHT_WHITE_BRICKS,
                            BlockInit.BRIGHT_BROWN_BRICKS,
                            BlockInit.BRIGHT_MAGENTA_BRICKS,
                            BlockInit.BRIGHT_ORANGE_BRICKS,
                            BlockInit.BRIGHT_PINK_BRICKS,
                            BlockInit.BRIGHT_PURPLE_BRICKS
                    ),
                    ItemCategory.Entry.create(BlockInit.LARGE_BROWN_BRICKS,
                            BlockInit.LARGE_BROWN_BRICKS,
                            BlockInit.LARGE_LIGHT_GRAY_BRICKS,
                            BlockInit.LARGE_WHITE_BRICKS
                    )
            )
            .build()
    );

    public static final ItemCategory CARPETS = ItemCategory.create(ItemCategory.builder()
            .setID("carpets")
            .addItems(
                    ItemCategory.Entry.create(BlockInit.CARPET_STAR_RED,
                            BlockInit.CARPET_STAR_RED,
                            BlockInit.CARPET_STAR_PINK,
                            BlockInit.CARPET_STAR_PURPLE,
                            BlockInit.CARPET_STAR_BLUE,
                            BlockInit.CARPET_STAR_CYAN,
                            BlockInit.CARPET_STAR_GREEN,
                            BlockInit.CARPET_STAR_ORANGE
                    ),
                    ItemCategory.Entry.create(BlockInit.CARPET_CONFETTI,
                            BlockInit.CARPET_CONFETTI
                    ),
                    ItemCategory.Entry.create(BlockInit.CARPET_CONFETTI_FREDBEARS,
                            BlockInit.CARPET_CONFETTI_FREDBEARS
                    ),
                    ItemCategory.Entry.create(BlockInit.CARPET_SPACE,
                            BlockInit.CARPET_SPACE
                    ),
                    ItemCategory.Entry.create(BlockInit.CARPET_TRIANGLE,
                            BlockInit.CARPET_TRIANGLE
                    ),
                    ItemCategory.Entry.create(BlockInit.CARPET_SWIRLY_RED,
                            BlockInit.CARPET_SWIRLY_RED
                    )
            )
            .build()
    );

    public static final ItemCategory WOOD = ItemCategory.create(ItemCategory.builder()
            .setID("wood")
            .addItems(
                    ItemCategory.Entry.create(BlockInit.STAGE_PLANKS,
                            BlockInit.STAGE_PLANKS,
                            BlockInit.DARK_STAGE_PLANKS,
                            BlockInit.LIGHT_STAGE_PLANKS
                    ),
                    ItemCategory.Entry.create(BlockInit.STAGE_PLANKS_THIN,
                            BlockInit.STAGE_PLANKS_THIN,
                            BlockInit.DARK_STAGE_PLANKS_THIN
                    ),
                    ItemCategory.Entry.create(BlockInit.WOODEN_LOWER_WALL,
                            BlockInit.WOODEN_LOWER_WALL,
                            BlockInit.WOODEN_LOWER_WALL_TRIMMED
                    )
            )
            .build()
    );

    public static final ItemCategory GLASS = ItemCategory.create(ItemCategory.builder()
            .setID("glass")
            .addItems(
                    ItemCategory.Entry.create(BlockInit.TILED_GLASS,
                            BlockInit.TILED_GLASS,
                            BlockInit.TILED_GLASS_SLIT,
                            BlockInit.TILED_GLASS_COLORED,
                            BlockInit.TILED_GLASS_SLIT_COLORED
                    ),
                    ItemCategory.Entry.create(BlockInit.BIG_WINDOW,
                            BlockInit.BIG_WINDOW,
                            BlockInit.BIG_WINDOW_WHITE,
                            BlockInit.BIG_WINDOW_DARK
                    ),
                    ItemCategory.Entry.create(BlockInit.DIRTY_GLASS,
                            BlockInit.DIRTY_GLASS
                    )
            )
            .build()
    );

    public static final ItemCategory BUILDING = ItemCategory.create(ItemCategory.builder()
            .setID("building")
            .addItems(
                    ItemCategory.Entry.create(BlockInit.CONCRETE_FLOOR,
                            BlockInit.CONCRETE_FLOOR,
                            BlockInit.CONCRETE_FLOOR_DARK,
                            BlockInit.CONCRETE_FLOOR_TILE
                    ),
                    ItemCategory.Entry.create(BlockInit.DARK_GRAY_CONCRETE,
                            BlockInit.DARK_GRAY_CONCRETE,
                            BlockInit.GRAY_CONCRETE_WALL,
                            BlockInit.GRAY_CONCRETE_WALL_SPLIT
                    ),
                    ItemCategory.Entry.create(BlockInit.GRAY_WALL,
                            BlockInit.GRAY_WALL,
                            BlockInit.DARK_GRAY_WALL
                    ),
                    ItemCategory.Entry.create(BlockInit.WHITE_DINER_WALL,
                            BlockInit.WHITE_DINER_WALL,
                            BlockInit.TAN_DINER_WALL
                    ),
                    ItemCategory.Entry.create(BlockInit.CEILING_TILES,
                            BlockInit.CEILING_TILES,
                            BlockInit.CEILING_TILES_STAINED,
                            BlockInit.BLACK_CEILING_TILE,
                            BlockInit.WHITE_CEILING_TILES
                    ),
                    ItemCategory.Entry.create(BlockInit.DARK_CEILING,
                            BlockInit.DARK_CEILING,
                            BlockInit.DARK_CEILING_DETAIL
                    ),
                    ItemCategory.Entry.create(BlockInit.CEILING_TILE_LIGHT,
                            BlockInit.CEILING_TILE_LIGHT
                    )
            )
            .build()
    );

    public static final ItemCategory OTHER = ItemCategory.create(ItemCategory.builder()
            .setID("other")
            .addItems(
                    ItemCategory.Entry.create(ItemInit.DECAL_BOOK,
                            ItemInit.DECAL_BOOK,
                            ItemInit.PAINTBRUSH,
                            ItemInit.SCRAPER,
                            ItemInit.PIPE_WRENCH
                    ),
                    ItemCategory.Entry.create(BlockInit.PLAIN_BLACK_BLOCK,
                            BlockInit.PLAIN_BLACK_BLOCK
                    ),
                    ItemCategory.Entry.create(BlockInit.CHEESE_BLOCK,
                            BlockInit.CHEESE_BLOCK,
                            BlockInit.CHEESE_BLOCK_WHITE
                    ),
                    ItemCategory.Entry.create(BlockInit.BALLPIT,
                            BlockInit.BALLPIT
                    ),
                    ItemCategory.Entry.create(BlockInit.MIMIC_FRAME,
                            BlockInit.MIMIC_FRAME,
                            BlockInit.MIMIC_FRAME_2x2,
                            BlockInit.MIMIC_FRAME_4x4,
                            BlockInit.MIMIC_FRAME_DIAGONAL
                    )
            )
            .build()
    );

    public static void registerItemCategories() {
        FnafUniverseRebuilt.LOGGER.info("Registering Item Categories for " + FnafUniverseRebuilt.MOD_ID);
    }
}
